name: Build Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Check the bash syntax
        run: |
          set -e
          bash -n build.sh 
      - name: Run the build
        run: |
          export DATE=$(date +%Y%m%d)

          echo $PASSWORD | docker login $REGISTRY -u $GITHUB_REPOSITORY_OWNER --password-stdin

          export IMAGE=$GITHUB_REPOSITORY

          docker build . --tag $REGISTRY/$IMAGE:$DATE --tag $REGISTRY/$IMAGE:latest
          docker push $REGISTRY/$IMAGE:latest
          docker push $REGISTRY/$IMAGE:$DATE
        env:
          REGISTRY: ghcr.io
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
